# Discover on demand
name: Discover CI On Demand

on:
  workflow_dispatch:
    inputs:
      experiment_name:
        required: true
        type: choice
        options:
          - ci-heartbeat
          - ci-clean
          - ci-cancel-slurm
          - geos_hs
      experiment_action:
        required: true
        type: choice
        options:
          - All
          - Validation
          - Benchmark
      geosongpu_ci_ref:
        required: true
        type: string
        default: main

defaults:
  run:
    shell: bash

jobs:
  run-discover-ondemand:
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosongpu-ondemand.yml@project/geosongpu
    with:
      experiment_name:   ${{ inputs.experiment_name }}
      experiment_action: ${{ inputs.experiment_action }}
      geosongpu_ci_ref : ${{ inputs.geosongpu_ci_ref }}
